// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txrjielutfxndpcwazgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4cmppZWx1dGZ4bmRwY3dhemdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzA2OTUsImV4cCI6MjA1NzM0NjY5NX0.0vZVtz_WxIlO--H0nDftV6QBUt6byBl47EHXji38RdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);