// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqeezagqtjmfliyuaytj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxZWV6YWdxdGptZmxpeXVheXRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODA0MzIsImV4cCI6MjA1NzM1NjQzMn0.pxsywLJHteT2YrkCRKCXmmjXkVwl1bCZp7g3mH_-P_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);